# Generated by Django 5.1.2 on 2024-12-03 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_2fa', models.BooleanField(default=False)),
                ('otp_secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('fk_user_id', models.OneToOneField(db_column='fk_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
