# Generated by Django 5.1.2 on 2024-12-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
