version: '3.9'

services:
  backend:
    image: eenghassaan/nativo_english_be:latest
    container_name: ne_api_backend
    env_file: .env  # Load environment variables from the .env file
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  # Referencing the variable from .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Referencing the variable from .env
      POSTGRES_DB: ${POSTGRES_DB}  # Referencing the variable from .env
      DATABSE_URL: ${DATABSE_URL}
    volumes:
      - ./staticfiles:/app/staticfiles  # Adjust to match where your static files are
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:17  # Use PostgreSQL version 17
    container_name: ne_db
    env_file: .env  # Load environment variables from the .env file for the db service
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  # Referencing the variable from .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Referencing the variable from .env
      POSTGRES_DB: ${POSTGRES_DB}  # Referencing the variable from .env
      DATABSE_URL: ${DATABSE_URL}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data:
