# Generated by Django 5.1.2 on 2024-12-01 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselesson',
            name='fk_course_id',
        ),
        migrations.AddField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_column='modified_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_enrollment_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_column='modified_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_enrollment_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursefeedback',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_feedback_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursefeedback',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_column='modified_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_feedback_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_column='modified_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courserating',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_rating_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courserating',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_column='modified_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_rating_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_content_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_column='modified_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_content_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=200, null=True)),
                ('section_description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_section_created', to=settings.AUTH_USER_MODEL)),
                ('fk_course_id', models.ForeignKey(db_column='fk_course_id', on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('modified_by', models.ForeignKey(blank=True, db_column='modified_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_section_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='courselesson',
            name='fk_section_id',
            field=models.ForeignKey(db_column='fk_section_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='course.coursesection'),
            preserve_default=False,
        ),
    ]
