# Generated by Django 5.1.2 on 2024-12-01 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_courselesson_fk_course_id_course_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(db_column='fk_owner_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='fk_course_id',
            field=models.ForeignKey(db_column='fk_course_id', on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='fk_user_id',
            field=models.ForeignKey(db_column='fk_user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursefeedback',
            name='fk_course_id',
            field=models.ForeignKey(db_column='fk_course_id', on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AlterField(
            model_name='coursefeedback',
            name='fk_user_id',
            field=models.ForeignKey(db_column='fk_user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courserating',
            name='fk_course_id',
            field=models.ForeignKey(db_column='fk_course_id', on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AlterField(
            model_name='courserating',
            name='fk_user_id',
            field=models.ForeignKey(db_column='fk_user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='fk_course_lesson_id',
            field=models.ForeignKey(db_column='fk_course_lesson_id', on_delete=django.db.models.deletion.CASCADE, to='course.courselesson'),
        ),
    ]
