# Generated by Django 5.1.2 on 2024-12-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='avg_rating',
            field=models.FloatField(default=0.0, max_length=5),
        ),
    ]
