# Generated by Django 5.1.2 on 2024-12-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncontent',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('video', 'video'), ('image', 'image')], default='text', max_length=10),
        ),
    ]
