# Generated by Django 5.1.2 on 2024-12-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_lessoncontent_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessoncontent',
            name='content_audio_url',
        ),
        migrations.RemoveField(
            model_name='lessoncontent',
            name='content_image_url',
        ),
        migrations.RemoveField(
            model_name='lessoncontent',
            name='content_video_url',
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='content_audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='content_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='content_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('video', 'Video'), ('image', 'Image')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='lesson_content_position',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
