# Generated by Django 5.1.2 on 2025-01-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncontent',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish')], max_length=7),
        ),
    ]
